#cloud-config
repo_update: true
repo_upgrade: all

# Параметр --ssh-key не работает, так что добавить вручную
# ERROR: --ssh-key flag conflicts with user-data metadata key. Please add your ssh key to user-data manually
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDy6APV5zlNLYCqOqmpPZHIWN7qLSk4qS3IRn32g+aM2 aleksandrkrzhn@yandex.ru

packages:
  - git

runcmd:
  - ['git', 'clone', 'https://github.com/Otus-DevOps-2022-11/aleksandrpnshkn_infra.git']
  - ['cd', 'aleksandrpnshkn_infra']
  - ['git', 'checkout', 'cloud-testapp']
  - ['./install_ruby.sh']
  - ['./install_mongodb.sh']
  - ['./deploy.sh']
