---
- name: Configure hosts and deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 158.160.61.246
  tasks:
    - name: Install dependencies
      become: true
      apt:
        name: git
        state: present
        update_cache: true
      tags:
        - app
        - deploy

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      tags:
        - app
        - deploy

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags:
        - app
        - deploy

    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags:
        - db
      notify: restart mongod

    - name: Add unit file for puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags:
        - app
      notify: restart puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags:
        - app

    - name: Enable puma
      become: true
      systemd:
        name: puma
        enabled: yes
      tags:
        - app

  handlers:
    - name: restart mongod
      become: true
      service:
        name: mongod
        state: restarted

    - name: restart puma
      become: true
      systemd:
        name: puma
        state: restarted
        daemon_reload: yes
